// // ____ tables ...
import {
  comments,
  departments,
  notifications,
  organizations,
  tasks,
  users,
  commentsTaskRelation,
  taskCommentsRelation,
  commentsRelationWithUser,
  userRelationWithComments,
  organizationRelationWithDepartments,
  departmentsRelationWithOrganization,
  taskAssignees,
  userTaskJunction,
  userTasks,
  usersTasksRelation,
  userDepartments,
  departmentUsers,
  userDepartmentsJunction,
  userDepartmentsRelation,
  userRelationWithNotifications,
  notificationsRelationWithUser,
  usersRelationWithOrganizations,
  organizationsRelationsWithUser,
  taskRelationsWithOrganization,
  organizationRelationsWithTasks,
} from "@/schemas";

export {
  comments,
  departments,
  notifications,
  organizations,
  tasks,
  users,
  commentsTaskRelation,
  taskCommentsRelation,
  commentsRelationWithUser,
  userRelationWithComments,
  organizationRelationWithDepartments,
  departmentsRelationWithOrganization,
  taskAssignees,
  userTaskJunction,
  userTasks,
  usersTasksRelation,
  userDepartments,
  departmentUsers,
  userDepartmentsJunction,
  userDepartmentsRelation,
  userRelationWithNotifications,
  notificationsRelationWithUser,
  usersRelationWithOrganizations,
  organizationsRelationsWithUser,
  taskRelationsWithOrganization,
  organizationRelationsWithTasks,
};
